// Generated by bin/sync.mjs — registry metadata WITHOUT component source.
// Safe to import from client components; the full registry (registryData.ts)
// must stay server-side only.

export interface RegistryMetaItem {
  name: string;
  type: string;
  description?: string;
  category?: string;
  typeLabel?: string;
  details?: string[];
  usage?: string[];
  codeNext?: string;
  isNew?: boolean;
  dependencies?: string[];
  files: { name: string; targetPath?: string }[];
}

export const registryMeta: Record<string, RegistryMetaItem> = {
  "GutterLines": {
    "name": "GutterLines",
    "type": "components:ui",
    "description": "A standard GutterLines component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "GutterLines.tsx",
        "targetPath": "components/ui/GutterLines.tsx"
      }
    ]
  },
  "accordion": {
    "name": "Accordion",
    "type": "components:ui",
    "description": "A Future UI Accordion component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "futureuikit",
      "lucide-react"
    ],
    "files": [
      {
        "name": "accordion.tsx",
        "targetPath": "components/ui/accordion.tsx"
      }
    ]
  },
  "ai-chat": {
    "name": "AI Chat Interface",
    "type": "components:ui",
    "description": "A Future UI AI Chat Interface component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "clsx",
      "framer-motion",
      "lucide-react",
      "react-markdown",
      "react-syntax-highlighter",
      "remark-gfm",
      "tailwind-merge"
    ],
    "files": [
      {
        "name": "ai-chat.tsx",
        "targetPath": "components/ui/ai-chat.tsx"
      }
    ]
  },
  "alert": {
    "name": "Alert",
    "type": "components:ui",
    "description": "Inline alert banners with solid, soft, and outline styles, icons, and dismissal.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "alert.tsx",
        "targetPath": "components/ui/alert.tsx"
      }
    ]
  },
  "alert-dialog": {
    "name": "Alert Dialog",
    "type": "components:ui",
    "description": "A standard Alert Dialog component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-alert-dialog",
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "alert-dialog.tsx",
        "targetPath": "components/ui/alert-dialog.tsx"
      },
      {
        "name": "button.tsx",
        "targetPath": "components/ui/button.tsx"
      }
    ]
  },
  "aspect-ratio": {
    "name": "Aspect Ratio",
    "type": "components:ui",
    "description": "A standard Aspect Ratio component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-aspect-ratio"
    ],
    "files": [
      {
        "name": "aspect-ratio.tsx",
        "targetPath": "components/ui/aspect-ratio.tsx"
      }
    ]
  },
  "automotive-carousel": {
    "name": "Automotive Carousel",
    "type": "components:ui",
    "description": "A Future UI Automotive Carousel component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "@react-three/drei",
      "@react-three/fiber",
      "class-variance-authority",
      "framer-motion",
      "lucide-react",
      "three",
      "three-stdlib"
    ],
    "files": [
      {
        "name": "automotive-carousel.tsx",
        "targetPath": "components/ui/automotive-carousel.tsx"
      },
      {
        "name": "button.tsx",
        "targetPath": "components/ui/button.tsx"
      },
      {
        "name": "basic-loader.tsx",
        "targetPath": "components/ui/basic-loader.tsx"
      }
    ]
  },
  "avatar": {
    "name": "Avatar",
    "type": "components:ui",
    "description": "An avatar with image fallback, status dot, colors, sizes, and stackable groups.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "avatar.tsx",
        "targetPath": "components/ui/avatar.tsx"
      }
    ]
  },
  "badge": {
    "name": "Badge",
    "type": "components:ui",
    "description": "A small status descriptor for UI elements.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "badge.tsx",
        "targetPath": "components/ui/badge.tsx"
      }
    ]
  },
  "basic-card": {
    "name": "Basic Card",
    "type": "components:ui",
    "description": "A Future UI Basic Card component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "basic-card.tsx",
        "targetPath": "components/ui/basic-card.tsx"
      }
    ]
  },
  "basic-loader": {
    "name": "Basic Loader",
    "type": "components:ui",
    "description": "A modern, animated loading indicator with multiple visual styles.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "basic-loader.tsx",
        "targetPath": "components/ui/basic-loader.tsx"
      }
    ]
  },
  "bento-grid": {
    "name": "Bento Grid",
    "type": "components:ui",
    "description": "A responsive bento feature grid with spanning tiles, hover glow, and staggered reveals.",
    "category": "layout",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "bento-grid.tsx",
        "targetPath": "components/ui/bento-grid.tsx"
      }
    ]
  },
  "bmw-m4": {
    "name": "BMW M4",
    "type": "components:ui",
    "description": "A premium 3D BMW M4 component with interactive orbit controls and cinematic lighting.",
    "category": "ui",
    "dependencies": [
      "@react-three/drei",
      "@react-three/fiber",
      "framer-motion",
      "three"
    ],
    "files": [
      {
        "name": "bmw-m4.tsx",
        "targetPath": "components/ui/bmw-m4.tsx"
      }
    ]
  },
  "boxy-bounce": {
    "name": "Bouncy Loader",
    "type": "components:ui",
    "description": "A Future UI Bouncy Loader component.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "boxy-bounce-loader.tsx",
        "targetPath": "components/ui/boxy-bounce-loader.tsx"
      }
    ]
  },
  "boxy-rotate": {
    "name": "Rotating Loader",
    "type": "components:ui",
    "description": "A Future UI Rotating Loader component.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "boxy-rotate-loader.tsx",
        "targetPath": "components/ui/boxy-rotate-loader.tsx"
      }
    ]
  },
  "boxy-shift": {
    "name": "Boxy Loader",
    "type": "components:ui",
    "description": "A Future UI Boxy Loader component.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "boxy-shift-loader.tsx",
        "targetPath": "components/ui/boxy-shift-loader.tsx"
      }
    ]
  },
  "breadcrumb": {
    "name": "Breadcrumb",
    "type": "components:ui",
    "description": "A standalone breadcrumb trail with separators, colors, and collapse support.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "lucide-react"
    ],
    "files": [
      {
        "name": "breadcrumb.tsx",
        "targetPath": "components/ui/breadcrumb.tsx"
      }
    ]
  },
  "browser-window": {
    "name": "Browser Window",
    "type": "components:ui",
    "description": "A Future UI Browser Window component.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "browser-window.tsx",
        "targetPath": "components/ui/browser-window.tsx"
      }
    ]
  },
  "button": {
    "name": "Button",
    "type": "components:ui",
    "description": "A Future UI Button component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "button.tsx",
        "targetPath": "components/ui/button.tsx"
      }
    ]
  },
  "calculator": {
    "name": "Calculator",
    "type": "components:ui",
    "description": "A Future UI Calculator component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "calculator.tsx",
        "targetPath": "components/ui/calculator.tsx"
      }
    ]
  },
  "calendar": {
    "name": "Calendar",
    "type": "components:ui",
    "description": "A Future UI Calendar component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "calendar.tsx",
        "targetPath": "components/ui/calendar.tsx"
      },
      {
        "name": "calendar-context.tsx",
        "targetPath": "components/ui/calendar-context.tsx"
      }
    ]
  },
  "card": {
    "name": "Card",
    "type": "components:ui",
    "description": "A set of modular card components including Header, Title, Description, Content, and Footer.",
    "category": "layout",
    "dependencies": [],
    "files": [
      {
        "name": "card.tsx",
        "targetPath": "components/ui/card.tsx"
      }
    ]
  },
  "checkbox": {
    "name": "Checkbox",
    "type": "components:ui",
    "description": "An animated checkbox with a spring check mark, colors, shapes, and label support.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "checkbox.tsx",
        "targetPath": "components/ui/checkbox.tsx"
      }
    ]
  },
  "cinematic-error": {
    "name": "Cinematic Error",
    "type": "components:ui",
    "description": "A Future UI Cinematic Error component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "cinematic-error.tsx",
        "targetPath": "components/ui/cinematic-error.tsx"
      }
    ]
  },
  "clay-morph-button": {
    "name": "Clay Morphism Button",
    "type": "components:ui",
    "description": "A premium, modern Claymorphism button with soft 3D extrusion, inner highlights, and tactile press effects.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "clay-morph-button.tsx",
        "targetPath": "components/ui/clay-morph-button.tsx"
      }
    ]
  },
  "collapsible": {
    "name": "Collapsible",
    "type": "components:ui",
    "description": "A Future UI Collapsible component with layout variants, color themes, and cinematic animations.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-collapsible",
      "class-variance-authority",
      "framer-motion",
      "futureuikit"
    ],
    "files": [
      {
        "name": "collapsible.tsx",
        "targetPath": "components/ui/collapsible.tsx"
      }
    ]
  },
  "command-palette": {
    "name": "Command Palette",
    "type": "components:ui",
    "description": "A premium command palette with subtle color themes and clean spacing.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-dialog",
      "@radix-ui/react-visually-hidden",
      "class-variance-authority",
      "cmdk",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "command-palette.tsx",
        "targetPath": "components/ui/command-palette.tsx"
      }
    ]
  },
  "component-page-sidebar": {
    "name": "Component Page Sidebar",
    "type": "components:ui",
    "description": "A collapsible navigation sidebar with theme switching, active route highlighting, and responsive layout support.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "framer-motion",
      "futureuikit",
      "lucide-react"
    ],
    "files": [
      {
        "name": "ComponentPageSidebar.tsx",
        "targetPath": "components/ui/ComponentPageSidebar.tsx"
      }
    ]
  },
  "components-grid": {
    "name": "Components Grid",
    "type": "components:ui",
    "description": "A responsive grid layout for displaying component cards with preview thumbnails.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "ComponentsGrid.tsx",
        "targetPath": "components/ui/ComponentsGrid.tsx"
      }
    ]
  },
  "context-menu": {
    "name": "Context Menu",
    "type": "components:ui",
    "description": "A Future UI Context Menu component with layout variants, color themes, and premium styling.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-context-menu",
      "lucide-react"
    ],
    "files": [
      {
        "name": "context-menu.tsx",
        "targetPath": "components/ui/context-menu.tsx"
      }
    ]
  },
  "cta-banner": {
    "name": "CTA Banner",
    "type": "components:ui",
    "description": "A call-to-action section with gradient, glass, and outline styles plus animated entrance.",
    "category": "layout",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "cta-banner.tsx",
        "targetPath": "components/ui/cta-banner.tsx"
      }
    ]
  },
  "cursor-glow-button": {
    "name": "Cursor Glow Button",
    "type": "components:ui",
    "description": "A Future UI Cursor Glow Button component with layout variants, color themes, and spacing options.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "cursor-glow-button.tsx",
        "targetPath": "components/ui/cursor-glow-button.tsx"
      }
    ]
  },
  "date-picker": {
    "name": "Date Picker",
    "type": "components:ui",
    "description": "A self-contained date picker with an animated popover calendar, month navigation, and colors.",
    "category": "form",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "date-picker.tsx",
        "targetPath": "components/ui/date-picker.tsx"
      }
    ]
  },
  "dock": {
    "name": "Dock",
    "type": "components:ui",
    "description": "A Future UI Dock component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "dock.tsx",
        "targetPath": "components/ui/dock.tsx"
      }
    ]
  },
  "dot-background": {
    "name": "Dot Background",
    "type": "components:ui",
    "description": "A Future UI Dot Background component.",
    "category": "ui",
    "dependencies": [],
    "files": [
      {
        "name": "dot-background.tsx",
        "targetPath": "components/ui/dot-background.tsx"
      }
    ]
  },
  "drawer": {
    "name": "Drawer",
    "type": "components:ui",
    "description": "A Future UI Drawer component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "drawer.tsx",
        "targetPath": "components/ui/drawer.tsx"
      },
      {
        "name": "button.tsx",
        "targetPath": "components/ui/button.tsx"
      }
    ]
  },
  "dropdown-menu": {
    "name": "Dropdown Menu",
    "type": "components:ui",
    "description": "A standard Dropdown Menu component with uniquely distinct premium variants and animations.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-dropdown-menu",
      "lucide-react"
    ],
    "files": [
      {
        "name": "dropdown-menu.tsx",
        "targetPath": "components/ui/dropdown-menu.tsx"
      }
    ]
  },
  "dynamic-form": {
    "name": "Dynamic Form System",
    "type": "components:ui",
    "description": "A Future UI Dynamic Form System component.",
    "category": "ui",
    "dependencies": [
      "@hookform/resolvers",
      "framer-motion",
      "lucide-react",
      "react-hook-form",
      "zod"
    ],
    "files": [
      {
        "name": "dynamic-form.tsx",
        "targetPath": "components/ui/dynamic-form.tsx"
      }
    ]
  },
  "empty-state": {
    "name": "Empty State",
    "type": "components:ui",
    "description": "A polished empty-state placeholder with icon, copy, and action slots.",
    "category": "feedback",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "empty-state.tsx",
        "targetPath": "components/ui/empty-state.tsx"
      }
    ]
  },
  "error-page": {
    "name": "Error Page",
    "type": "components:ui",
    "description": "A Future UI Error Page component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "error-page.tsx",
        "targetPath": "components/ui/error-page.tsx"
      },
      {
        "name": "button.tsx",
        "targetPath": "components/ui/button.tsx"
      }
    ]
  },
  "expanding-card": {
    "name": "Expanding Flex Card",
    "type": "components:ui",
    "description": "A Future UI Expanding Flex Card component.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "expanding-flex-card.tsx",
        "targetPath": "components/ui/expanding-flex-card.tsx"
      }
    ]
  },
  "faq": {
    "name": "FAQ",
    "type": "components:ui",
    "description": "A frequently-asked-questions section with smooth height animation and accessible disclosure.",
    "category": "layout",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "faq.tsx",
        "targetPath": "components/ui/faq.tsx"
      }
    ]
  },
  "file-upload": {
    "name": "FileUpload",
    "type": "components:ui",
    "description": "A Future UI FileUpload component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "file-upload.tsx",
        "targetPath": "components/ui/file-upload.tsx"
      }
    ]
  },
  "filter-builder": {
    "name": "Filter Builder",
    "type": "components:ui",
    "description": "A Future UI Filter Builder component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "clsx",
      "framer-motion",
      "lucide-react",
      "tailwind-merge"
    ],
    "files": [
      {
        "name": "filter-builder.tsx",
        "targetPath": "components/ui/filter-builder.tsx"
      }
    ]
  },
  "footer": {
    "name": "Footer",
    "type": "components:ui",
    "description": "A minimal, modern footer component with branding, navigation links, and external social links.",
    "category": "ui",
    "dependencies": [],
    "files": [
      {
        "name": "footer.tsx",
        "targetPath": "components/ui/footer.tsx"
      }
    ]
  },
  "form-builder": {
    "name": "FormBuilder",
    "type": "components:ui",
    "description": "A Future UI FormBuilder component.",
    "category": "ui",
    "dependencies": [
      "@hookform/resolvers",
      "framer-motion",
      "lucide-react",
      "react-hook-form",
      "zod"
    ],
    "files": [
      {
        "name": "form-builder.tsx",
        "targetPath": "components/ui/form-builder.tsx"
      }
    ]
  },
  "glass-panel": {
    "name": "Glass Panel",
    "type": "components:ui",
    "description": "A Future UI Glass Panel component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "glass-panel.tsx",
        "targetPath": "components/ui/glass-panel.tsx"
      }
    ]
  },
  "global-breadcrumb": {
    "name": "Global Breadcrumb",
    "type": "components:ui",
    "description": "A dynamic breadcrumb navigation component that generates navigation paths based on the current route, category, and component hierarchy.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "lucide-react"
    ],
    "files": [
      {
        "name": "global-breadcrumb.tsx",
        "targetPath": "components/ui/global-breadcrumb.tsx"
      }
    ]
  },
  "glowy": {
    "name": "Glowy Button",
    "type": "components:ui",
    "description": "A Future UI Glowy Button component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "glowy-button.tsx",
        "targetPath": "components/ui/glowy-button.tsx"
      }
    ]
  },
  "header": {
    "name": "Header",
    "type": "components:ui",
    "description": "A Future UI Header component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "futureuikit",
      "lucide-react"
    ],
    "files": [
      {
        "name": "header.tsx",
        "targetPath": "components/ui/header.tsx"
      }
    ]
  },
  "highlighter": {
    "name": "Highlighter",
    "type": "components:ui",
    "description": "A standard Highlighter component.",
    "category": "ui",
    "dependencies": [
      "motion",
      "rough-notation"
    ],
    "files": [
      {
        "name": "highlighter.tsx",
        "targetPath": "components/ui/highlighter.tsx"
      }
    ]
  },
  "hover-card": {
    "name": "Hover Card",
    "type": "components:ui",
    "description": "A standard Hover Card component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-hover-card"
    ],
    "files": [
      {
        "name": "hover-card.tsx",
        "targetPath": "components/ui/hover-card.tsx"
      }
    ]
  },
  "hover-glare-card": {
    "name": "Hover Glare Card",
    "type": "components:ui",
    "description": "A Future UI Hover Glare Card component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "hover-glare-card.tsx",
        "targetPath": "components/ui/hover-glare-card.tsx"
      }
    ]
  },
  "icon-cloud": {
    "name": "Icon Cloud",
    "type": "components:ui",
    "description": "A standard Icon Cloud component.",
    "category": "ui",
    "dependencies": [],
    "files": [
      {
        "name": "icon-cloud.tsx",
        "targetPath": "components/ui/icon-cloud.tsx"
      }
    ]
  },
  "infinite-slider": {
    "name": "Infinite Carousel Slider",
    "type": "components:ui",
    "description": "A Future UI Infinite Carousel Slider component.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "carousel-slider.tsx",
        "targetPath": "components/ui/carousel-slider.tsx"
      }
    ]
  },
  "input": {
    "name": "Input",
    "type": "components:ui",
    "description": "A premium text input with variants, colors, sizes, and icon slots.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "input.tsx",
        "targetPath": "components/ui/input.tsx"
      }
    ]
  },
  "input-otp": {
    "name": "Input Otp",
    "type": "components:ui",
    "description": "A standard Input Otp component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "input-otp",
      "lucide-react"
    ],
    "files": [
      {
        "name": "input-otp.tsx",
        "targetPath": "components/ui/input-otp.tsx"
      }
    ]
  },
  "kanban": {
    "name": "Kanban Board",
    "type": "components:ui",
    "description": "A Future UI Kanban Board component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "clsx",
      "framer-motion",
      "lucide-react",
      "tailwind-merge"
    ],
    "files": [
      {
        "name": "kanban.tsx",
        "targetPath": "components/ui/kanban.tsx"
      }
    ]
  },
  "kbd": {
    "name": "Kbd",
    "type": "components:ui",
    "description": "A keyboard-key chip for shortcuts, with sizes and key-combo grouping.",
    "category": "utility",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "kbd.tsx",
        "targetPath": "components/ui/kbd.tsx"
      }
    ]
  },
  "label": {
    "name": "Label",
    "type": "components:ui",
    "description": "A form label with size and color variants, plus required-field indicator.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "label.tsx",
        "targetPath": "components/ui/label.tsx"
      }
    ]
  },
  "menu": {
    "name": "Circle Navigation Menu",
    "type": "components:ui",
    "description": "A Future UI Circle Navigation Menu component.",
    "category": "ui",
    "dependencies": [
      "lucide-react"
    ],
    "files": [
      {
        "name": "nav-menu.tsx",
        "targetPath": "components/ui/nav-menu.tsx"
      }
    ]
  },
  "menubar": {
    "name": "Menubar",
    "type": "components:ui",
    "description": "A standard Menubar component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-menubar",
      "lucide-react"
    ],
    "files": [
      {
        "name": "menubar.tsx",
        "targetPath": "components/ui/menubar.tsx"
      }
    ]
  },
  "minimal-button": {
    "name": "Minimal Button",
    "type": "components:ui",
    "description": "An ultra-clean, premium, modern button inspired by Vercel, Linear, and Stripe. Focuses on typography, precise spacing, and subtle interactions.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "minimal-button.tsx",
        "targetPath": "components/ui/minimal-button.tsx"
      }
    ]
  },
  "modal": {
    "name": "Modal",
    "type": "components:ui",
    "description": "A Future UI Modal component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-dialog",
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "modal.tsx",
        "targetPath": "components/ui/modal.tsx"
      }
    ]
  },
  "navbar": {
    "name": "Navbar",
    "type": "components:ui",
    "description": "A standalone responsive navbar with glass blur, scroll elevation, and an animated mobile menu.",
    "category": "navigation",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "navbar.tsx",
        "targetPath": "components/ui/navbar.tsx"
      }
    ]
  },
  "nexus-card": {
    "name": "Nexus Card",
    "type": "Cards",
    "description": "A Future UI Nexus Card component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "nexus-card.tsx",
        "targetPath": "components/ui/nexus-card.tsx"
      }
    ]
  },
  "noir-hero-3d": {
    "name": "Noir Hero 3D",
    "type": "components:ui",
    "description": "A Future UI Noir Hero 3D component.",
    "category": "ui",
    "dependencies": [
      "@react-three/drei",
      "@react-three/fiber",
      "three"
    ],
    "files": [
      {
        "name": "noir-hero-3d.tsx",
        "targetPath": "components/ui/noir-hero-3d.tsx"
      }
    ]
  },
  "otp-input": {
    "name": "Premium OTP Input",
    "type": "components:ui",
    "description": "A highly polished OTP verification component with persistent glowing borders, spring-powered overlapping transitions, and in-box icon morphing.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "otp-input.tsx",
        "targetPath": "components/ui/otp-input.tsx"
      }
    ]
  },
  "otp-verification": {
    "name": "OTP Verification",
    "type": "components:ui",
    "description": "An animated OTP input component with verification states, success and error feedback, keyboard navigation, and paste support.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "otp-verification.tsx",
        "targetPath": "components/ui/otp-verification.tsx"
      }
    ]
  },
  "pagination": {
    "name": "Pagination",
    "type": "components:ui",
    "description": "A standard Pagination component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slot",
      "class-variance-authority",
      "lucide-react"
    ],
    "files": [
      {
        "name": "pagination.tsx",
        "targetPath": "components/ui/pagination.tsx"
      },
      {
        "name": "button.tsx",
        "targetPath": "components/ui/button.tsx"
      }
    ]
  },
  "particles": {
    "name": "Particles",
    "type": "components:ui",
    "description": "A Future UI Particles component.",
    "category": "ui",
    "dependencies": [],
    "files": [
      {
        "name": "particles.tsx",
        "targetPath": "components/ui/particles.tsx"
      }
    ]
  },
  "perspective-grid": {
    "name": "Perspective Grid",
    "type": "components:ui",
    "description": "A Future UI Perspective Grid component.",
    "category": "ui",
    "dependencies": [],
    "files": [
      {
        "name": "perspective-grid.tsx",
        "targetPath": "components/ui/perspective-grid.tsx"
      }
    ]
  },
  "point-cursor": {
    "name": "Point Cursor",
    "type": "components:ui",
    "description": "A Future UI Point Cursor component.",
    "category": "ui",
    "dependencies": [
      "clsx",
      "framer-motion",
      "tailwind-merge"
    ],
    "files": [
      {
        "name": "PointCursor.tsx",
        "targetPath": "components/ui/PointCursor.tsx"
      }
    ]
  },
  "popover": {
    "name": "Popover",
    "type": "components:ui",
    "description": "A dependency-free popover primitive with spring entrance, side/align placement, and outside-click dismissal.",
    "category": "overlay",
    "isNew": true,
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "popover.tsx",
        "targetPath": "components/ui/popover.tsx"
      }
    ]
  },
  "premium-upload-button": {
    "name": "Premium Upload Button",
    "type": "components:ui",
    "description": "A premium, highly interactive file upload button with various design variants, success states, and robust error handling.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "premium-upload-button.tsx",
        "targetPath": "components/ui/premium-upload-button.tsx"
      }
    ]
  },
  "pricing": {
    "name": "Pricing",
    "type": "components:ui",
    "description": "A premium pricing section with tier cards, a monthly/yearly toggle, and a highlighted plan.",
    "category": "layout",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "pricing.tsx",
        "targetPath": "components/ui/pricing.tsx"
      }
    ]
  },
  "primary": {
    "name": "Primary Button",
    "type": "components:ui",
    "description": "A Future UI Primary Button component.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "primary-button.tsx",
        "targetPath": "components/ui/primary-button.tsx"
      }
    ]
  },
  "progress": {
    "name": "Progress",
    "type": "components:ui",
    "description": "Animated linear and circular progress indicators with colors and sizes.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "progress.tsx",
        "targetPath": "components/ui/progress.tsx"
      }
    ]
  },
  "project-deck": {
    "name": "Project Deck",
    "type": "components:ui",
    "description": "A 3D stacked deck of project cards with hover fan-out and flip animation.",
    "category": "ui",
    "dependencies": [
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "project-deck.tsx",
        "targetPath": "components/ui/project-deck.tsx"
      }
    ]
  },
  "puzzle-video": {
    "name": "Puzzle Video",
    "type": "components:ui",
    "description": "A cinematic storytelling component where physical puzzle pieces seamlessly assemble into a premium glass video container.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "puzzle-video.tsx",
        "targetPath": "components/ui/puzzle-video.tsx"
      }
    ]
  },
  "radio-group": {
    "name": "Radio Group",
    "type": "components:ui",
    "description": "A standard Radio Group component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-radio-group",
      "lucide-react"
    ],
    "files": [
      {
        "name": "radio-group.tsx",
        "targetPath": "components/ui/radio-group.tsx"
      }
    ]
  },
  "resizable": {
    "name": "Resizable",
    "type": "components:ui",
    "description": "A standard Resizable component.",
    "category": "ui",
    "dependencies": [
      "lucide-react",
      "react-resizable-panels@^2.1.9"
    ],
    "files": [
      {
        "name": "resizable.tsx",
        "targetPath": "components/ui/resizable.tsx"
      }
    ]
  },
  "rich-text-editor": {
    "name": "Rich Text Editor",
    "type": "components:ui",
    "description": "A Future UI Rich Text Editor component.",
    "category": "ui",
    "dependencies": [
      "@tailwindcss/typography",
      "@tiptap/core",
      "@tiptap/extension-color",
      "@tiptap/extension-highlight",
      "@tiptap/extension-image",
      "@tiptap/extension-link",
      "@tiptap/extension-placeholder",
      "@tiptap/extension-table",
      "@tiptap/extension-table-cell",
      "@tiptap/extension-table-header",
      "@tiptap/extension-table-row",
      "@tiptap/extension-task-item",
      "@tiptap/extension-task-list",
      "@tiptap/extension-text-align",
      "@tiptap/extension-text-style",
      "@tiptap/extension-underline",
      "@tiptap/pm",
      "@tiptap/react",
      "@tiptap/starter-kit",
      "@tiptap/suggestion",
      "class-variance-authority",
      "clsx",
      "lucide-react",
      "tailwind-merge",
      "tippy.js"
    ],
    "files": [
      {
        "name": "rich-text-editor.tsx",
        "targetPath": "components/ui/rich-text-editor.tsx"
      }
    ]
  },
  "scifi-helmet": {
    "name": "Sci-Fi Helmet",
    "type": "components:ui",
    "description": "A premium 3D Sci-Fi Helmet component with interactive orbit controls and cinematic lighting.",
    "category": "ui",
    "dependencies": [
      "@react-three/drei",
      "@react-three/fiber",
      "framer-motion",
      "three"
    ],
    "files": [
      {
        "name": "scifi-helmet.tsx",
        "targetPath": "components/ui/scifi-helmet.tsx"
      }
    ]
  },
  "scroll-area": {
    "name": "Scroll Area",
    "type": "components:ui",
    "description": "A standard Scroll Area component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-scroll-area"
    ],
    "files": [
      {
        "name": "scroll-area.tsx",
        "targetPath": "components/ui/scroll-area.tsx"
      }
    ]
  },
  "scroll-progress": {
    "name": "Scroll Progress",
    "type": "components:ui",
    "description": "A high-performance scroll progress indicator with smooth spring-based animations powered by Framer Motion.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "ScrollProgress.tsx",
        "targetPath": "components/ui/ScrollProgress.tsx"
      }
    ]
  },
  "scroll-text-reveal": {
    "name": "Scroll Text Reveal",
    "type": "components:ui",
    "description": "A text reveal animation on scroll.",
    "category": "ui",
    "dependencies": [
      "clsx",
      "framer-motion",
      "tailwind-merge"
    ],
    "files": [
      {
        "name": "scroll-text-reveal.tsx",
        "targetPath": "components/ui/scroll-text-reveal.tsx"
      }
    ]
  },
  "search": {
    "name": "Search",
    "type": "components:ui",
    "description": "A Future UI Search component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "search.tsx",
        "targetPath": "components/ui/search.tsx"
      }
    ]
  },
  "search-input": {
    "name": "Search Input",
    "type": "components:ui",
    "description": "A Future UI Search Input component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "search-input.tsx",
        "targetPath": "components/ui/search-input.tsx"
      }
    ]
  },
  "select": {
    "name": "Select",
    "type": "components:ui",
    "description": "A Future UI Select component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-popover",
      "@radix-ui/react-slot",
      "@tanstack/react-virtual",
      "class-variance-authority",
      "cmdk",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "select.tsx",
        "targetPath": "components/ui/select.tsx"
      }
    ]
  },
  "separator": {
    "name": "Separator",
    "type": "components:ui",
    "description": "Horizontal and vertical dividers with solid, dashed, and gradient styles plus inline labels.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "separator.tsx",
        "targetPath": "components/ui/separator.tsx"
      }
    ]
  },
  "sidebar": {
    "name": "Sidebar",
    "type": "components:ui",
    "description": "A collapsible app-shell sidebar with animated width, grouped nav items, and badges.",
    "category": "navigation",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "sidebar.tsx",
        "targetPath": "components/ui/sidebar.tsx"
      }
    ]
  },
  "sidebar-button": {
    "name": "Sidebar Button",
    "type": "components:ui",
    "description": "A Future UI Sidebar Button component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "sidebar-button.tsx",
        "targetPath": "components/ui/sidebar-button.tsx"
      }
    ]
  },
  "skeleton": {
    "name": "Skeleton",
    "type": "components:ui",
    "description": "A standard Skeleton component.",
    "category": "ui",
    "dependencies": [],
    "files": [
      {
        "name": "skeleton.tsx",
        "targetPath": "components/ui/skeleton.tsx"
      }
    ]
  },
  "skeuomorphic-button": {
    "name": "Skeuomorphic Button",
    "type": "components:ui",
    "description": "A premium, production-ready skeuomorphic button with realistic depth, tactile interactions, and modern aesthetics.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "SkeuomorphicButton.tsx",
        "targetPath": "components/ui/SkeuomorphicButton.tsx"
      }
    ]
  },
  "slide-up-reveal": {
    "name": "Slide Up Reveal",
    "type": "components:ui",
    "description": "A premium futuristic reveal component that feels like physically lifting a landscape cloth to reveal an OS underneath.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "slide-up-reveal.tsx",
        "targetPath": "components/ui/slide-up-reveal.tsx"
      }
    ]
  },
  "slider": {
    "name": "Slider",
    "type": "components:ui",
    "description": "A standard Slider component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-slider",
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "slider.tsx",
        "targetPath": "components/ui/slider.tsx"
      }
    ]
  },
  "sonner": {
    "name": "Sonner",
    "type": "components:ui",
    "description": "A standard Sonner component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "lucide-react",
      "next-themes",
      "sonner"
    ],
    "files": [
      {
        "name": "sonner.tsx",
        "targetPath": "components/ui/sonner.tsx"
      }
    ]
  },
  "stats": {
    "name": "Stats",
    "type": "components:ui",
    "description": "A stats section with spring count-up numbers that animate when scrolled into view.",
    "category": "layout",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "stats.tsx",
        "targetPath": "components/ui/stats.tsx"
      }
    ]
  },
  "stepper": {
    "name": "Stepper",
    "type": "components:ui",
    "description": "A multi-step progress indicator with animated connectors, spring check marks, and vertical mode.",
    "category": "navigation",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "stepper.tsx",
        "targetPath": "components/ui/stepper.tsx"
      }
    ]
  },
  "switch": {
    "name": "Switch",
    "type": "components:ui",
    "description": "A spring-animated toggle switch with colors, sizes, shapes, and label support.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "switch.tsx",
        "targetPath": "components/ui/switch.tsx"
      }
    ]
  },
  "table": {
    "name": "Table",
    "type": "components:ui",
    "description": "Clean, composable table primitives with striped, bordered, and hoverable styles.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "table.tsx",
        "targetPath": "components/ui/table.tsx"
      }
    ]
  },
  "tabs": {
    "name": "Tabs",
    "type": "components:ui",
    "description": "Animated tabs with a sliding indicator, multiple variants, colors, and shapes.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion"
    ],
    "files": [
      {
        "name": "tabs.tsx",
        "targetPath": "components/ui/tabs.tsx"
      }
    ]
  },
  "terminal": {
    "name": "Terminal",
    "type": "components:ui",
    "description": "A premium, highly customizable terminal window component with authentic styling for various OS variants (macOS, Windows, Ubuntu, etc) and built-in animations.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "terminal.tsx",
        "targetPath": "components/ui/terminal.tsx"
      }
    ]
  },
  "testimonials": {
    "name": "Testimonials",
    "type": "components:ui",
    "description": "A testimonial section with star ratings, shown as an infinite marquee or a static grid.",
    "category": "layout",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "testimonials.tsx",
        "targetPath": "components/ui/testimonials.tsx"
      }
    ]
  },
  "text-3d-flip": {
    "name": "Text 3d Flip",
    "type": "components:ui",
    "description": "A standard Text 3d Flip component.",
    "category": "ui",
    "dependencies": [
      "motion"
    ],
    "files": [
      {
        "name": "text-3d-flip.tsx",
        "targetPath": "components/ui/text-3d-flip.tsx"
      }
    ]
  },
  "text-system": {
    "name": "Typography System",
    "type": "components:ui",
    "description": "A Future UI Typography System component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "typography.tsx",
        "targetPath": "components/ui/typography.tsx"
      }
    ]
  },
  "textarea": {
    "name": "Textarea",
    "type": "components:ui",
    "description": "A premium textarea with variants, colors, and optional auto-resize.",
    "category": "ui",
    "isNew": true,
    "dependencies": [
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "textarea.tsx",
        "targetPath": "components/ui/textarea.tsx"
      }
    ]
  },
  "theme-toggle": {
    "name": "Theme Toggle",
    "type": "components:ui",
    "description": "An animated dark/light mode toggle that flips the `dark` class and persists the choice.",
    "category": "utility",
    "isNew": true,
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "theme-toggle.tsx",
        "targetPath": "components/ui/theme-toggle.tsx"
      }
    ]
  },
  "toast": {
    "name": "Toast Notification",
    "type": "components:ui",
    "description": "A Future UI Toast Notification component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-toast",
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "toast.tsx",
        "targetPath": "components/ui/toast.tsx"
      },
      {
        "name": "toaster.tsx",
        "targetPath": "components/ui/toaster.tsx"
      },
      {
        "name": "use-toast.ts",
        "targetPath": "hooks/use-toast.ts"
      }
    ]
  },
  "toggle": {
    "name": "Toggle",
    "type": "components:ui",
    "description": "A Future UI Premium Toggle component (Switch) with CVA architecture.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "framer-motion",
      "lucide-react"
    ],
    "files": [
      {
        "name": "toggle.tsx",
        "targetPath": "components/ui/toggle.tsx"
      }
    ]
  },
  "toggle-group": {
    "name": "Toggle Group",
    "type": "components:ui",
    "description": "A premium Toggle Group component with dynamic colors and variants.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-toggle-group",
      "class-variance-authority"
    ],
    "files": [
      {
        "name": "toggle-group.tsx",
        "targetPath": "components/ui/toggle-group.tsx"
      }
    ]
  },
  "tooltip": {
    "name": "Tooltip",
    "type": "components:ui",
    "description": "A standard Tooltip component.",
    "category": "ui",
    "dependencies": [
      "@radix-ui/react-tooltip"
    ],
    "files": [
      {
        "name": "tooltip.tsx",
        "targetPath": "components/ui/tooltip.tsx"
      }
    ]
  },
  "typing-animation": {
    "name": "Typing Animation",
    "type": "components:ui",
    "description": "A standard Typing Animation component.",
    "category": "ui",
    "dependencies": [
      "motion"
    ],
    "files": [
      {
        "name": "typing-animation.tsx",
        "targetPath": "components/ui/typing-animation.tsx"
      }
    ]
  },
  "velocity-marquee": {
    "name": "Velocity Marquee",
    "type": "components:ui",
    "description": "An interactive marquee grid of glowing cards.",
    "category": "ui",
    "dependencies": [
      "framer-motion"
    ],
    "files": [
      {
        "name": "velocity-marquee.tsx",
        "targetPath": "components/ui/velocity-marquee.tsx"
      },
      {
        "name": "marquee-track.tsx",
        "targetPath": "components/ui/marquee-track.tsx"
      }
    ]
  },
  "workflow-builder": {
    "name": "Workflow Builder",
    "type": "components:ui",
    "description": "A Future UI Workflow Builder component.",
    "category": "ui",
    "dependencies": [
      "class-variance-authority",
      "clsx",
      "framer-motion",
      "lucide-react",
      "tailwind-merge"
    ],
    "files": [
      {
        "name": "workflow-builder.tsx",
        "targetPath": "components/ui/workflow-builder.tsx"
      }
    ]
  }
};
